// Code generated by github.com/edwarnicke/imports-gen DO NOT EDIT.
package imports

import (
	_ "context"
	_ "github.com/antonfisher/nested-logrus-formatter"
	_ "github.com/edwarnicke/serialize"
	_ "github.com/kelseyhightower/envconfig"
	_ "github.com/networkservicemesh/sdk/pkg/tools/log"
	_ "github.com/networkservicemesh/sdk/pkg/tools/log/logruslogger"
	_ "github.com/networkservicemesh/sdk/pkg/tools/opentelemetry"
	_ "github.com/sirupsen/logrus"
	_ "k8s.io/apimachinery/pkg/apis/meta/v1"
	_ "k8s.io/apimachinery/pkg/runtime/schema"
	_ "k8s.io/apimachinery/pkg/runtime/serializer"
	_ "k8s.io/client-go/kubernetes"
	_ "k8s.io/client-go/kubernetes/scheme"
	_ "k8s.io/client-go/rest"
	_ "k8s.io/clusterproperty/api/v1alpha1"
	_ "os"
	_ "os/signal"
	_ "syscall"
	_ "time"
)
